services:
  db:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: postgres        
      POSTGRES_PASSWORD: postgres   
      POSTGRES_DB: stock_master_dev        
    ports:
      - "5432:5432"  
    volumes:
      - postgres_data:/var/lib/postgresql/data 

volumes:
  postgres_data:
    driver: local
